### ISSUE TITLE
Python integer comparison failure under Solaris 10 causes not generating performance data

### ISSUE THREAD

**Issue by guilhemmarchand** [guilhemmarchand/TA-nmon#11]
Under Solaris 10, Python even if running 2.7.x fails to compare integer not explicitly set as integer. (int)

This results in failing to compare between last checkpoint and last data in raw data, and causes performance data not to be generated.

This unexpected situation seems to affect only Solaris 10 running Python, it can be solved easily by setting explicitly integers during processing steps.

**Comment by graciellamauri** [comment]
please, how could i define setting explicitly integers during processing steps? I don' t know how to do this. :(

I installed TA-nmon...that's working very fine at AIX but at Solaris although apparently executing, the nmon_data isnt been generated. This is a Solaris 11.

**Comment by graciellamauri** [comment]
I confirmed that's not an indexing issue...the nmon_data files are not been generated and TA-nmon processes are active.

**Comment by guilhemmarchand** [comment]
@graciellamauri 

Hi,

I would need to ahead and verify, Solaris isn't very common nowadays.

Basically following this:

https://ta-nmon.readthedocs.io/en/latest/troubleshoot.html

Would help getting a clue.
